import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {QueryClient} from "@tanstack/query-core";
import {QueryClientProvider} from "@tanstack/react-query";
import {ReactQueryProvider} from "~/services/QueryClientProvider";
import Sidebar from "~/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ReactQueryProvider >
    <html lang="en">
      <body className={inter.className+'text-black dark:text-white bg-gray-200 dark:bg-gray-900'}>
    <div className={'flex '}><Sidebar/>
        <div className={'mt-4 w-full h-full'}>{children}</div></div>  </body>
    </html></ReactQueryProvider>
  );
}
